### PR TITLE
use ledcWrite if analogWrite is not available

### LINKED ISSUE #3: [ESP32] error: 'analogWrite' was not declared in this scope
When trying to compile this library for ESP32 using PlatformIO the following error occurs:

```
.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp: In member function 'int8_t Mux::write(uint8_t, int8_t)':
.pio/libdeps/lolin32/Analog-Digital Multiplexers_ID5363/src/Mux.cpp:121:32: error: 'analogWrite' was not declared in this scope
     analogWrite(signalPin, data);
                                ^
```

platformio config:

```ini
[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino

lib_deps =
  Analog-Digital Multiplexers
```

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #3

also see https://github.com/espressif/arduino-esp32/issues/4

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @stechio

**Comment by thijstriemstra** [comment]
I made additional changes to fix compilation, I'm using this branch for now: https://github.com/thijstriemstra/arduino-ad-mux-lib/tree/esp32-support

use it by adding it to platformio.ini:

```ini
lib_deps =
  ; use fork, see https://github.com/stechio/arduino-ad-mux-lib/pull/4
  Analog-Digital Multiplexers=https://github.com/thijstriemstra/arduino-ad-mux-lib/archive/esp32-support.zip
```

**Comment by ketan** [comment]
I've tested that this PR works fine with esp32. Please merge when you can.

**Comment by stechio** [comment]
Nice confirmation, @ketan! [As previously stated](https://github.com/stechio/arduino-ad-mux-lib/issues/3#issuecomment-653492397), I'm willing to merge it -- as soon as I can.
thanks

**Comment by stechio** [comment]
The fix has been included in the [next major dev branch](https://github.com/stechio/arduino-ad-mux-lib/tree/feat/dev3), as [it contextually required an incompatible name clash fix](https://github.com/stechio/arduino-ad-mux-lib/issues/3#issuecomment-665927242).

**Pull request merged**
