### PR TITLE
ci: add travis config

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@stechio can you enable Travis for this repository? See https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

**Comment by thijstriemstra** [comment]
Travis build on my fork shows some issues: https://travis-ci.org/github/thijstriemstra/arduino-ad-mux-lib/jobs/713241359

**Comment by stechio** [comment]
You are perfectly right: now [dev 3 branch has Travis CI enabled](https://github.com/stechio/arduino-ad-mux-lib/issues/3#issuecomment-667167089), thank you!

**Comment by thijstriemstra** [comment]
Unfortunate that my contribution didn't get merged but copied instead. I put some time and effort in creating this pull request..

**Comment by stechio** [comment]
I didn't merge it because I didn't copy it: my configuration is based on [an article from Pololu](https://www.pololu.com/blog/654/continuous-testing-for-arduino-libraries-using-platformio-and-travis-ci), which links [a demonstrative sample](https://github.com/pololu/dual-vnh5019-motor-shield/blob/6604394006b5c2f6a31a0407826771a96ac1782f/.travis.yml).

I intended to acknowledge your contributions in the CREDITS file (to include in the project), but you are probably right: the proper workflow was to apply changes to your thijstriemstra:travis-ci branch and merge it... Sorry for my fault :(

**Pull request closed without merging**
